nc: 1 # Liczba klas (osoby)
depth_multiple: 0.33
width_multiple: 0.25

backbone:
  - [-1, 1, Conv, [16, 3, 2, 1]]
  - [-1, 1, Conv, [32, 3, 2]]
  - [-1, 3, C2f, [32, True]]
  - [-1, 1, Conv, [64, 3, 2]]
  - [-1, 6, C2f, [64, True]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [-1, 6, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]
  - [-1, 3, C2f, [256, True]]

head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]]
  - [-1, 3, C2f, [128]]
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]]
  - [-1, 3, C2f, [64]]
  - [-1, 1, Conv, [64, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]
  - [-1, 3, C2f, [128]]
  - [-1, 1, Conv, [128, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]
  - [-1, 3, C2f, [256]]
  - [[15, 18, 21], 1, Detect, [nc]]
